version: '3.3'

services:
  snetdb-node-1:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: snetdb-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: snetdb
      MYSQL_USER: snetuser
      MYSQL_PASSWORD: snetuser
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - snet-network
    ports:
      - 3360:3306
    volumes:
      - snetdb-node-1-data:/var/lib/mysql

  snetdb-node-2:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: snetdb-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: snetdb
      MYSQL_USER: snetuser
      MYSQL_PASSWORD: snetuser
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - snet-network
    ports:
      - 3361:3306
    volumes:
      - snetdb-node-2-data:/var/lib/mysql

  snetdb-node-3:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: snetdb-node-3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: snetdb
      MYSQL_USER: snetuser
      MYSQL_PASSWORD: snetuser
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - snet-network
    ports:
      - 3362:3306
    volumes:
      - snetdb-node-3-data:/var/lib/mysql
      
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    healthcheck:
      test: "/usr/bin/mysql --user=snetuser --password=snetuser --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    depends_on:
      - snetdb-node-1
      - snetdb-node-2
      - snetdb-node-3
      
    networks:
      - snet-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    networks:
      - snet-network
    volumes: 
      - cache:/data

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_INIT_LIMIT: 5
    networks:
      - snet-network

  kafka-node-1:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - '2181:2181'
      - '9092:9092'
    networks:
      - snet-network
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_HOST_NAME: kafka-node-1
        ADVERTISED_PORT: 9092
        ADVERTISED_HOST_NAME: kafka-node-1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CREATE_TOPICS: "event_server:1:1"

  writer:
    build:
      context: ../
      dockerfile: Docker/social_network/Dockerfile
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_DATABASE=snetdb
      - DB_LOGIN=snetuser
      - DB_PASSWORD=snetuser
      - CACHE=cache:6379
      - QUEUE_HOST=kafka-node-1:9092
      - QUEUE_TOPIC=event_server
      - QUEUE_GROUP_ID=0
    entrypoint: Software-Arch/socialnet/build/writer_main
    networks:
      - snet-network
    depends_on:
      - snetdb-node-1
      - snetdb-node-2
      - snetdb-node-3
      - proxysql
      - cache
      - kafka-node-1

  social_network:
    build:
      context: ../
      dockerfile: Docker/social_network/Dockerfile
    container_name: social_network
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=snetuser
      - DB_PASSWORD=snetuser
      - DB_DATABASE=snetdb
      - CACHE=cache:6379
      - QUEUE_HOST=kafka-node-1:9092
      - QUEUE_TOPIC=event_server
      - QUEUE_GROUP_ID=0
    ports:
      - 8080:8080
    networks:
      - snet-network
    depends_on:
      - proxysql
      - cache
      - snetdb-node-1
      - snetdb-node-2
      - snetdb-node-3
      # proxysql:
      #   condition: service_healthy

volumes:
  snetdb-node-1-data:
  snetdb-node-2-data:
  snetdb-node-3-data:
  proxysql-data:
  cache:

networks:
  snet-network:
    driver: "bridge"
    external: false
