openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Software-Arch Social Net API'
  description: API пользователя для второго (3го) домашнего задания по курсу Архитектура ПО
servers:
  - url: http://localhost:8080
    description: Example server
paths:
  /search:
    get:
      summary: Поиск пользователей по маске имени и фамилии
      parameters:
      - name: first_name
        description: Имя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Found users for the provided masks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No users found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected Error. Oops! Something went wrong! X/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /search_by_login:
    get:
      summary: Поиск пользователя по логину
      parameters:
      - name: login
        description: Логин
        in: query
        required: true
        schema:
          type: string      
      responses:
        '200':
          description: Found users for the provided login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No users found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected Error. Oops! Something went wrong! X/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /search_by_id:
    get:
      summary: Поиск пользователя по id
      parameters:
      - name: id
        description: id
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'     
      responses:
        '200':
          description: Found users for the provided id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/users'
        404:
          description: No users found for the provided mask
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected Error. Oops! Something went wrong! X/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth:
    get:
      summary: Проверка авторизации (аутентификации)
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not authorized
          content:
            application/json:
              schema:
                type: string
  /user:
    get:
      summary: Вывод информации о пользователе
      parameters:
      - name: id
        description: Уникальный id пользователя
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        404:
          description: User Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected Error. Oops! Something went wrong! X/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Добавление нового пользователя
      parameters:
      - name: first_name
        description: Имя пользователя
        in: query
        required: true
        schema:
          type: string
      - name: last_name
        description: Фамилия пользователя
        in: query
        required: true
        schema:
          type: string
      - name: email
        description: email пользователя
        in: query
        required: true
        schema:
          type: string
      - name: birthday
        description: Дата дня рождения пользователя 
        in: query
        required: true
        schema:
          type: string
      - name: login
        description: login пользователя
        in: query
        required: true
        schema:
          type: string
      - name: password
        description: пароль пользователя
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ID of freshly registered user
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Registration Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected Error. Oops! Something went wrong! X/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /message:
    get:
      summary: Получение списка сообщений между пользователями
      description: Метод возвращает сообщения для указанных пользователей
      parameters:
      - name: id_from
        description: Уникальный id автора отправителя сообщений
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      - name: id_to
        description: Уникальный id автора получателя сообщений
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
      responses:
        '200':
          description: Message history of id_to and id_from
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messages'
        404:
          description: No author found for the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messages'
        500:
          description: Unexpected Error. Oops! Something went wrong! X/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Send message
      parameters:
      - name: id_from
        description: id автора - отправителя сообщения
        in: query
        required: true
        schema:
          type: string
      - name: id_to
        description: id автора - получателя сообщения
        in: query
        required: true
        schema:
          type: string
      - name: message
        description: Message contents. Message is created.
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: id сообщения
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Error while sending the message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected Error. Oops! Something went wrong! X/
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /wall:
        post:
            summary: Добавление новой записи на стену пользователя
            parameters:
                - name: user_id
                  description: id пользователя
                  in: query
                  required: true
                  schema:
                    type: integer                
                - name: post_title
                  in: query
                  description: Заголовок поста
                  required: true
                  schema:
                      type: string
                - name: post_text
                  in: query
                  description: Содержание поста
                  required: true
                  schema:
                      type: string                      
            responses:
                "200":
                    description: id поста
                    content:
                        application/json:
                         schema:
                          type: integer            
                404:
                    description: Error while posting new wall post
                    content:
                        application/json:
                         schema:
                            $ref: '#/components/schemas/Error'
                500:
                    description: Unexpected Error. Oops! Something went wrong! X/
                    content:
                        application/json:
                         schema:
                            $ref: '#/components/schemas/Error'
        get:
            summary: Получение списка записей на стене пользователя
            parameters:
                - name: user_id
                  in: query
                  description: id стены (текущего пользователя)
                  required: true
                  schema:
                      type: integer
            responses:
                '200':
                    description: Successfully loaded wall posts
                    content:
                     application/json:
                      schema:
                        $ref: '#/components/schemas/wall'   
                404:
                    description: Error while loading wall posts
                    content:
                        application/json:
                         schema:
                            $ref: '#/components/schemas/Error'
                500:
                    description: Unexpected Error. Oops! Something went wrong! X/
                    content:
                        application/json:
                         schema:
                            $ref: '#/components/schemas/Error'   

components:
  schemas:
    user_id:
      description: Уникальный id пользователя
      type: integer
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    user:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - birthday
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        birthday:
          type: string
        login:
          type: string
        password:
          type: string
    messages:
      type: array
      items:
        $ref: '#/components/schemas/message'
    message:
      type: object
      properties:
        id:
          type: string
        id_from:
          type: string
        id_to:
          type: string
        message:
          type: string

    post_id:
          type: integer
          description: Уникальный id стены       
    walls:
          type: array
          items:
              $ref: "#/components/schemas/wall"
    wall:
          type: object
          required:
              - id
              - user_id
              - post_text
          properties:
             id:
                $ref: '#/components/schemas/post_id'   
             user_id:
                 type: integer
             post_text:
                 type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: An Error Occured. Unexpected Error. Oops! Something went wrong! X/
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []